### ISSUE TITLE
vwv pixel shader code is too complex

### ISSUE THREAD

**Issue by khusmann** [visionworkbench/visionworkbench#19]
When trying to run vwv on my netbook (with a less than powerful graphics card), I get the error:

```i915_program_error: Exceeded max instructions (213 out of 123)```

This is because the fragment shader code (https://github.com/visionworkbench/visionworkbench/blob/master/src/vw/gui/GlPreviewWidget.cc#L37) has too many nested-if statements.

To minimize the number of instructions in the shader, it would be better to break that single pixel shader into multiple shaders that are swapped in depending on what function (channel select, hillshade, etc) is selected. This way it would run on graphics cards like mine.

**Comment by ScottMcMichael** [comment]
This code was moved to the graveyard.
