### ISSUE TITLE
linking libvw doesn't work on osx

### ISSUE THREAD

**Issue by khusmann** [visionworkbench/visionworkbench#21]
For some reason, linking with libvw doesn't work on osx. Instead, libCore libMath, etc must be individually linked. 

I'm not sure if this is related, but on linux I find that an ldd of libvw outputs:

        libvwCore-2.1.0_post.so => not found
        libvwMath-2.1.0_post.so => not found
        libvwImage-2.1.0_post.so => not found
        libvwFileIO-2.1.0_post.so => not found

**Comment by ScottMcMichael** [comment]
This is probably a user configuration issue.
