### ISSUE TITLE
RpcChannel.cc errors

### ISSUE THREAD

**Issue by rbeyer** [visionworkbench/visionworkbench#27]
When I run make on Vision Workbench, it moves along happily, and then gives these errors:

RpcChannel.cc: In member function 'void vw::platefile::IChannel::send_message(vw::platefile::RpcWrapper&)':
RpcChannel.cc:45: error: invalid use of undefined type 'struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'struct vw::platefile::RpcWrapper'
RpcChannel.cc:46: error: invalid use of undefined type 'struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'struct vw::platefile::RpcWrapper'
RpcChannel.cc:49: error: invalid use of undefined type 'struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'struct vw::platefile::RpcWrapper'
RpcChannel.cc: In member function 'vw::int32 vw::platefile::IChannel::recv_message(vw::platefile::RpcWrapper&)':
RpcChannel.cc:57: error: invalid use of undefined type 'struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'struct vw::platefile::RpcWrapper'
RpcChannel.cc:59: error: invalid use of undefined type 'struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'struct vw::platefile::RpcWrapper'
RpcChannel.cc: In static member function 'static vw::uint32 vw::platefile::IChannel::checksum(const vw::platefile::RpcWrapper&)':
RpcChannel.cc:119: error: invalid use of undefined type 'const struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'const struct vw::platefile::RpcWrapper'
RpcChannel.cc:119: error: invalid use of undefined type 'const struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'const struct vw::platefile::RpcWrapper'
RpcChannel.cc:120: error: invalid use of undefined type 'const struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'const struct vw::platefile::RpcWrapper'
RpcChannel.cc:120: error: invalid use of undefined type 'const struct vw::platefile::RpcWrapper'
/Users/rbeyer/software/visionworkbench/src/vw/Plate/RpcChannel.h:18: error: forward declaration of 'const struct vw::platefile::RpcWrapper'
make[6]: *** [RpcChannel.lo] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

My guess is that the protobuffer files where the RpcWrapper class is defined are not properly pulled in, but I don't know enough about how protobuffers work to debug it.

**Comment by oleg-alexandrov** [comment]
Nothing else to do here. Plate is dead.
