### ISSUE TITLE
VW FileIO test failed

### ISSUE THREAD

**Issue by panovr** [visionworkbench/visionworkbench#31]
[----------] 1 test from DiskCacheImageView
[ RUN      ] DiskCacheImageView.Construction
unknown file: Failure
C++ exception with description "DiskImageResourceTIFF: Failed to open "/tmp/vw_cache_iGON1K.tif" for reading!" thrown in the test body.
[  FAILED  ] DiskCacheImageView.Construction (1 ms)
[----------] 1 test from DiskCacheImageView (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (2 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DiskCacheImageView.Construction

 1 FAILED TEST
FAIL: TestDiskImageView

**Comment by ScottMcMichael** [comment]
Need more information to address this, may be a config issue.
