### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [visionworkbench/visionworkbench#35]
I would like to point out that identifiers like "[`__VW_BUNDLE_ADJUSTMENT_H__`](https://github.com/visionworkbench/visionworkbench/blob/0503635ab040f215302726206fe387d19bc1187d/src/vw/BundleAdjustment.h#L26)" and "[`__MATH_STATISTICS_H__`](https://github.com/visionworkbench/visionworkbench/blob/6121eb0ab107c0b14c889ef0bfbc982ec068d2da/src/vw/Math/Statistics.h#L23)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by oleg-alexandrov** [comment]
That would be nice. A pull request is welcome.
