### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [visionworkbench/visionworkbench#36]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [ImageInterestData](https://github.com/visionworkbench/visionworkbench/blob/aa54f81a258e4900047d5ccfa570213ce84ac606/src/vw/InterestPoint/InterestData.h#L206)
- [LogInstance](https://github.com/visionworkbench/visionworkbench/blob/213906ca8312796b64e1e4781f63cb547844480c/src/vw/Core/Log.h#L387)

**Comment by oleg-alexandrov** [comment]
I looked at the code. I agree. Even better, if a smart pointer is used there, one would not even need to use the delete operator anywhere, not in the destructor, or when reusing the pointer for some other value.
