### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [visionworkbench/visionworkbench#37]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](http://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [fit_parameters](https://github.com/visionworkbench/visionworkbench/blob/213906ca8312796b64e1e4781f63cb547844480c/src/vw/Stereo/AffineMixtureComponent.h#L311)
- [MinimumSpanningTree](https://github.com/visionworkbench/visionworkbench/blob/213906ca8312796b64e1e4781f63cb547844480c/src/vw/Math/MinimumSpanningTree.cc#L44)
- [write_comments](https://github.com/visionworkbench/visionworkbench/blob/213906ca8312796b64e1e4781f63cb547844480c/src/vw/FileIO/DiskImageResourcePNG.cc#L492)

**Comment by oleg-alexandrov** [comment]
I looked at the code you point to. I think even std::vector would do in this context, or else, smart pointers. You are welcome to submit a pull request (I am aware 5 years elapsed. :)
