### ISSUE TITLE
GDAL 2.x compatibility

### ISSUE THREAD

**Issue by schwehr** [visionworkbench/visionworkbench#41]
Hi all,

There have been a ton of changes in the last year+ going from GDAL 1.11.x to GDAL 2.y.z.  Looking at the head of master, it looks like DiskImageResourceGDAL.cc is likely to see the same issue.  Hopefully pretty easy to just check the results.  These happen to be from 2.0.  And there are likely to be more in GeoReferenceResourceGDAL.cc

```
VisionWorkbench/src/vw/FileIO/DiskImageResourceGDAL.cc:610:13: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
        band->RasterIO( GF_Read, bbox.min().x(), bbox.min().y(), bbox.width(), bbox.height(),
        ^~~~~~~~~~~~~~
VisionWorkbench/src/vw/FileIO/DiskImageResourceGDAL.cc:619:9: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    band->RasterIO( GF_Read, bbox.min().x(), bbox.min().y(), bbox.width(), bbox.height(),
    ^~~~~~~~~~~~~~
VisionWorkbench/src/vw/FileIO/DiskImageResourceGDAL.cc:660:11: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
      band->RasterIO( GF_Write, bbox.min().x(), bbox.min().y(), bbox.width(), bbox.height(),
```

**Comment by oleg-alexandrov** [comment]
Thank you for letting us know. We don't plan to upgrade to the newest GDAL yet, would be non-trivial work and I am not sure about the benefits. I'll will keep your note in mind.

**Comment by schwehr** [comment]
Sorry, I didn't mean for you all to update to GDAL 2.x for you work, but I think the solution to remove the warning will be the same for both GDAL 1.11.x and GDAL 2.x.  I'm just at the point where I'm finally able to turn off -w suppression of all warnings as two of us have just gotten GDAL 2.x to build warning free for the first last a couple weeks ago.  I'll see if we can get a pull request that can provide a #if around the RasterIO call that lets the code work with both.  e.g. based on the notes here:

https://trac.osgeo.org/gdal/browser/trunk/gdal/MIGRATION_GUIDE.TXT#L74

GDAL 1.11 branch - https://trac.osgeo.org/gdal/browser/branches/1.11/gdal/gcore/gdal_priv.h#L359

     CPLErr      RasterIO( GDALRWFlag, int, int, int, int,
                          void *, int, int, GDALDataType,
                          int, int *, int, int, int );

GDAL head - https://trac.osgeo.org/gdal/browser/trunk/gdal/gcore/gdal_priv.h#L454

    CPLErr      RasterIO( GDALRWFlag, int, int, int, int,
                          void *, int, int, GDALDataType,
                          int, int *, GSpacing, GSpacing, GSpacing,
                          GDALRasterIOExtraArg* psExtraArg
    #ifndef DOXYGEN_SKIP
                          OPTIONAL_OUTSIDE_GDAL(NULL)
    #endif
                          ) CPL_WARN_UNUSED_RESULT;


So it should just be checking the CPLErr code and doing what ever VW normally does for warnings if the return is CE_Failure or CE_Fatal.  CPLError is here:

https://trac.osgeo.org/gdal/browser/trunk/gdal/port/cpl_error.h#L48

    typedef enum
    {
        CE_None = 0,
        CE_Debug = 1,
        CE_Warning = 2,
        CE_Failure = 3,
        CE_Fatal = 4
    } CPLErr;

**Comment by oleg-alexandrov** [comment]
Thank you, a patch would be welcome.

**Comment by schwehr** [comment]
https://github.com/visionworkbench/visionworkbench/pull/42
