### ISSUE TITLE
get_n_unique_integers() fails once in a blue moon.

### ISSUE THREAD

**Issue by bjornpiltz** [visionworkbench/visionworkbench#43]
Actually once in RAND_MAX times. The problem is this line:
`samples[i] = int( (double(std::rand()) / double(RAND_MAX)) * size )
`
When rand() returns it's maximum value, _samples[i]_ is assigned _size_, when it should never be higher than _size-1_.

**Comment by ScottMcMichael** [comment]
Should be fixed by ec91b6fe41393edb44048ed38874d6b700d53c75
