### ISSUE TITLE
C++11?

### ISSUE THREAD

**Issue by aaronyonas** [visionworkbench/visionworkbench#45]
How do the owners and maintainers of VisionWorkbench feel about changes that use C++11 features?

Is the VW community ready to make that jump or is backwards compatibility more important?  (A third option: we could #ifdef all C++11 constructs--at the expense of added complexity.)

In my experience, VW is _much_ nicer to work with in a C++11 context.  Judicious use of C++11 features in VW itself could make the code simpler and perhaps faster.

(Thanks to Matt Hancher for suggesting that I put this question to the larger group.)

Best regards,
Aaron Yonas

**Comment by oleg-alexandrov** [comment]
Well, let's put it this way. There is no paid effort to maintain this
library on its own (though we do make changes to it as we need them for
Stereo Pipeline).

We have recently upgraded our compilers, so they are now able to ingest
C++-11. And yeah, C++-11 is cute (as long as one does not go too mad about
lambda functions).

That being said, I doubt we'll gain much from this upgrade, and nobody can
do the work anyway. C++-11 is basically syntactic sugar to me, and this
being a numerical library, it won't change much if in places newer and
fancier notation is used.

**Comment by aaronyonas** [comment]
I wasn't suggesting a library-wide "upgrade."  Rather, I was wondering if I could include C++11 features in  future pull requests.
The issue that prompted this question was a narrow one: Currently the min and max values for a channel can't be used in compile-time expressions.  The following C++11 tweak would fix that:

```
 template <class T, bool>
  struct ChannelRangeHelper {
    static inline constexpr T max() {
      return std::numeric_limits<T>::max();
    }
    static inline constexpr T min() {
      return T();
    }
  };

  // Channel range helper for floating-point types
  template <class T>
  struct ChannelRangeHelper<T,false> {
    static inline constexpr T max() {
      return (T)(1.0);
    }
    static inline constexpr T min() {
      return (T)(0.0);
    }
  };
```

**Comment by ScottMcMichael** [comment]
I am not sure that it is worth adding this new requirement for minor changes like that.  Are there any significant upgrades or improvements you are planning on making using C++11?  The main concern is that if a change like this causes any problems in Stereo Pipeline we don't have the resources to debug it.

**Comment by oleg-alexandrov** [comment]
As of recently, VW and ASP compile with C++-11 enabled. We had to do that to keep up with our dependencies, particularly ISIS.
