### ISSUE TITLE
Potential Security Vulnerability In Visionworkbench

### ISSUE THREAD

**Issue by leonjuranic** [visionworkbench/visionworkbench#47]
Hi,

We have discovered potential security vulnerability in visionworkbench.
Since it's sensitive information, to whom should we send details about it?
Contact e-mail would be nice.

Regards,
Leon Juranic
leon[at]defensecode.com
http://www.defensecode.com/

**Comment by oleg-alexandrov** [comment]
Our is not mission-critical code. I am sure there are bugs here and there, but hey, it is research code. I appreciate you reaching out, however.
