### ISSUE TITLE
PinholeModel coordinate vectors not fully supported

### ISSUE THREAD

**Issue by ScottMcMichael** [visionworkbench/visionworkbench#48]
The three coordinate vectors (u, v, and w directions) in the PinholeModel class are not handled everywhere in the code and failures will happen if they are used.  Map projection seems to work but bundle adjustment fails.

**Comment by oleg-alexandrov** [comment]
I think we should wipe those. I got bitten by that in the past in a different context. Not having u, v, w would make the code more readable, and I have never found an instance when the extra flexibility afforded by making yet another coordinate transform in the camera with these (whether a rotation or a flip) is necessary (though for some strange sensors it could be needed maybe).

**Comment by dshean** [comment]
I agree with @oleg-alexandrov.  A more complex sensor should have its own sensor model.  Most of the time, we just need a simple pinhole model and these additional vectors are confusing.

**Comment by oleg-alexandrov** [comment]
This is documented in https://stereopipeline.readthedocs.io/en/latest/pinholemodels.html and it is implicitly assumed that the user will never modify u, v, w from the defaults.  We have tools nowadays that produce camera models based on SfM, GCP, so there's less of a need to manually tinker with anything.
