### ISSUE TITLE
Bounding box empty handling

### ISSUE THREAD

**Issue by ScottMcMichael** [visionworkbench/visionworkbench#52]
Use of the bounding box class is not consistent between whether it is inclusive or exclusive of the end coordinate.  This leads to unwanted behavior such as functions failing to have their effect because min()[1] == max()[1].

**Comment by oleg-alexandrov** [comment]
Known problem, no good fix. A local fix at the location showing problem is the only thing we can do, and we should be aware of this each time we use this class. Still not as bad as the bug I found a while ago where the union of two empty boxes was non-empty. :)

**Comment by oleg-alexandrov** [comment]
I think the ultimate solution here is to have two classes, SemiOpenBBox (current one) and ClosedBBox (new one). The user would need to carefully pick the right one depending on what he wants to accomplish. One should not be allowed to implicitly cast from one type to another.

**Comment by oleg-alexandrov** [comment]
And did you fix the particular problem that lead you here?

**Comment by oleg-alexandrov** [comment]
Various fixes were added over the years in locations where it is important to distinguish between a fully empty box and a box that has only point. These usually amount to expanding the box a little bit. One gotcha is that the perfectly normal box [0, 1) x [0, 1), if viewed as integer box is just the point (0, 0), and after some processing on integer this easily results in a box like [0, 0] x [0, 0], which is then treated as the empty box. So a minefield.
