### ISSUE TITLE
Fix gtest on OSX

### ISSUE THREAD

**Issue by ScottMcMichael** [visionworkbench/visionworkbench#54]
Google Test is broken on newer versions of OSX.  Upgrading from v1.6 to v1.8 may fix this but VW uses a modified version of gtest with no documentation about how or why it was modified.  The proper long-term solution is probably to replace VW's custom gtest setup with a conventional gtest setup using the latest version.

**Comment by ScottMcMichael** [comment]
This is now working except for a few tests in VW.  These are in Math/LinearAlgebra and Camera/CameraGeometry.  It is not clear what is going on or how significant these are so for now they are disabled on the Mac so that the other unit tests can be run.

**Comment by oleg-alexandrov** [comment]
Having a regression testsuite with actual examples of tools doing work on real data seems to be working better than gtests. May need to get them back to work but that would require in duplication of effort each time some new feature breaks both the regression and the unit tests.
