### ISSUE TITLE
Proj 5 API

### ISSUE THREAD

**Issue by schwehr** [visionworkbench/visionworkbench#55]
Visionworkbench has some issues with Proj 5 that can be seen sometimes with TSAN.  They aren't mine, so I can't give details.

For reference, Even made a patch to GDAL to use Proj 5.0.1:

https://trac.osgeo.org/gdal/changeset/41878 by Even Rouault

**Comment by ScottMcMichael** [comment]
We do not support Proj 5 so you will have to Proj 4 with VW.  Are you seeing a problem with the existing code?

**Comment by schwehr** [comment]
Yes, there is trouble with existing VW code.  There are issues with Proj in VW that started somewhere in the last 6 months or so in Proj head.  The old API is still there in Proj 5.   That's where the trouble is.  I'll have to leave talking about the details to someone who is actually a user of VW.  I'm not personally using or debugging it.

I just wanted to make sure the trouble at least has a placeholder that others can find.  I'm fine if you want to close this bug.

This will likely come up again as, for example, proj 5.0.0 is in debian testing and unstable:
https://tracker.debian.org/pkg/proj

**Comment by ScottMcMichael** [comment]
Vision Workbench is only tested with the dependency versions used in BinaryBuilder, we don't have the need or the resources to update it to match the latest version of all of the dependencies.  The current supported versions are gdal v2.02 and proj 4.8.0.  Consider using BinaryBuilder to compile VW, it will automatically fetch compatible dependencies.

To any users attempting a manual compilation with proj 5, best of luck!
