### ISSUE TITLE
Fail to compile the latest VW, on Ubuntu 18.04

### ISSUE THREAD

**Issue by ghtao00** [visionworkbench/visionworkbench#62]
Hi,
   When building ASP using BinaryBuilder, all other libraries were built successfully except VW. I'm running into compile errors as following(Ubuntu 18.04, gcc 7.3.0). Any ideas on what's causing the problem? Thanks!
-----------------------------------------------------------------------------------
error 1: no type named 'type' in **
-----------------------------------------------------------------------------------
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/PerPixelViews.h: In instantiation of 'class vw::UnaryPerPixelView<vw::ImageView<vw::PixelRGBA<short int> >, vw::SelectChannelFunctor<vw::ImageView<vw::PixelRGBA<short int> > > >':
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Mosaic/ImageComposite.h:535:38:   required from 'vw::ImageView<PixelT> vw::mosaic::ImageComposite<PixelT>::blend_patch(const BBox2i&) const [with PixelT = vw::PixelRGBA<short int>; vw::BBox2i = vw::math::BBox<int, 2>]'
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Mosaic/ImageComposite.h:254:30:   required from 'vw::ImageView<PixelT> vw::mosaic::ImageComposite<PixelT>::generate_patch(const BBox2i&) const [with PixelT = vw::PixelRGBA<short int>; vw::BBox2i = vw::math::BBox<int, 2>]'
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Mosaic/ImageComposite.h:275:28:   required from 'vw::mosaic::ImageComposite<PixelT>::pixel_type vw::mosaic::ImageComposite<PixelT>::operator()(int, int, int) const [with PixelT = vw::PixelRGBA<short int>; vw::mosaic::ImageComposite<PixelT>::pixel_type = vw::PixelRGBA<short int>]'
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/ImageViewRef.h:161:91:   required from 'vw::ImageViewRefImpl<ViewT>::pixel_type vw::ImageViewRefImpl<ViewT>::operator()(vw::int32, vw::int32, vw::int32) const [with ViewT = vw::mosaic::ImageComposite<vw::PixelRGBA<short int> >; vw::ImageViewRefImpl<ViewT>::pixel_type = vw::PixelRGBA<short int>; vw::int32 = int]'
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/tools/image2qtree_help.cc:35:146:   required from here
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/PerPixelViews.h:107:81: error: no type named 'type' in 'struct boost::result_of<vw::SelectChannelFunctor<vw::ImageView<vw::PixelRGBA<short int> > >(vw::PixelRGBA<short int>)>'
     typedef typename boost::result_of<FuncT(typename ImageT::pixel_type)>::type                  result_type;
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/PerPixelViews.h:108:98: error: no type named 'type' in 'struct boost::result_of<vw::SelectChannelFunctor<vw::ImageView<vw::PixelRGBA<short int> > >(vw::PixelRGBA<short int>)>'
     typedef typename boost::remove_cv<typename boost::remove_reference<result_type>::type>::type pixel_type;
-------------------------------------------------------------------------------------------
error 2:  template argument deduction/substitution failed
-------------------------------------------------------------------------------------------
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/ImageMath.h:278:143: note:   template argument deduction/substitution failed:
/home/ghtao/ASP/projects/BinaryBuilder/build_asp/build/visionworkbench/visionworkbench-git/src/vw/../vw/Image/ImageMath.h:278:479: note: candidate: template<class Image1T, class Image2T> typename boost::enable_if_c<vw::IsMasked<typename Image2T::pixel_type>::value, const Image1T&>::type vw::operator/=(const vw::ImageViewBase<ImageT>&, const vw::ImageViewBase<View2T>&)
   VW_IMAGE_MATH_BINARY_IP_II_FUNCTION_ENABLE_IF( IsMasked<typename Image2T::pixel_type>::value, operator /=, vw::ArgArgInPlaceMaskedSafeQuotientFunctor )
-------------------------------------------------------------------------------------------

**Comment by ScottMcMichael** [comment]
We have not compiled before on Ubuntu 18.04 so you would be in new territory with this.  Are you sure you need to compile from scratch instead of using our binaries available for download?  https://ti.arc.nasa.gov/tech/asr/groups/intelligent-robotics/ngt/stereo/

**Comment by ghtao00** [comment]
Thank you!  Then which version of ubuntu was tested to be ok? I am trying to make a new class on LinescanModel to test some ideas, and need to compile it.

**Comment by ScottMcMichael** [comment]
I have compiled it on Ubuntu 16.04 using GCC 5.4.  I am sure that you can get it to work on 18.04 with some work but as you have seen the heavy use of templates can create some very tricky compile problems.

**Comment by ghtao00** [comment]
It seems that there are lots work to do when compiling on Ubuntu 18.04. Can I download the binaries  of VisionWorkbench library from somewhere, and I can use it directly and only need to compile ASP. Thank you!

**Comment by ScottMcMichael** [comment]
We don't provide separate VisionWorkbench installations, and even if we did I think you would still have to work through the same compile problems when compiling ASP.  If you can't change your OS you may still be able to get an older version of GCC working on it, maybe by compiling it yourself.  That would get you closer to our build environment and might reduce the number of errors.

Scott

________________________________

**Comment by ghtao00** [comment]
Thank you for your advice!

**Comment by ghtao00** [comment]
I installed gcc5.5.0, and could compile  VW and ASP successfully!

**Comment by ScottMcMichael** [comment]
Congratulations!  One day we will have to compile on GCC 7, but that day is not this day!

**Comment by Junxen** [comment]
> I installed gcc5.5.0, and could compile VW and ASP successfully!

hi tao. I am trying to build VM on Ubuntu18 as well. Can you detail how you complied ti?

**Comment by ScottMcMichael** [comment]
If you are trying to recreate this feat be aware that we have made changes to our build system to make some use of the Conda build system that ISIS now uses.  We still can't provide much help in building it but we hope to do more work on the build system next year to make it easier to use.

**Comment by ghtao00** [comment]
The process will depend on your linux version, gcc version and other configurations, and it is not an easy work to build vw and asp on local computer. 
Build.py is a good tool and will facilitate the build process.
