### ISSUE TITLE
Efficient subpixel image registration algorithms

### ISSUE THREAD

**Issue by excllent123** [visionworkbench/visionworkbench#63]
Hi   

Can you share some idea on improving the perfermance of  Upsample,according to this survey
Phase correlation with sub-pixel accuracy A comparative study in 1Dand 2D
Fitting is much faster than Upsample,  Will you implement other method?

Thanks

**Comment by ScottMcMichael** [comment]
Is there a particular test case where the existing code is not working well?  If there is something simple we can do to improve things we can add it.

**Comment by excllent123** [comment]
If the image is blur or textureless  ,the result is wrong 
In some review, Sinc  fitting is  better than upsamp, I have implemneted  QuadFit and  Local center of mass,but the result is bad.

**Comment by excllent123** [comment]
If  modify the coefficient of  Raised-cosine filter,the result may be right,but it's hard to find a right coefficient

**Comment by excllent123** [comment]
Windows function  is important, I implement windows funtion based on 
https://github.com/sidneycadot/WindowFunctions，but i dont'konw which  window function  is best
