### ISSUE TITLE
ipmatch - more RANSAC constraint?

### ISSUE THREAD

**Issue by adehecq** [visionworkbench/visionworkbench#65]
If I'm correct, ipmatch only accepts complex RANSAC constraints like similarity or homography. In many cases, the only transformation I expect between my images are a translation, and possibly a (small) rotation.
Would it be difficult to add more constraint to allow just for these kind of transformations? For some historical, scanned, images I have a lot of low quality IPs and ipmatch tend to favor matches that have large scaling and translation, which I know is not the case. Constraining RANSAC to simple transformation would help excluding outliers.
Thanks!

**Comment by oleg-alexandrov** [comment]
That tool was not touched for maybe a decade. 

It also has the "fundamental" transform which I don't know what is about. 

That it is having such a hard time even with a similarity transform it may likely mean that even the translation mode many not help you so much. 

You could try going back to ipfind and see if the default sift or obalog does any better. If you set it to produce a huge lot of IP, it may do a better job maybe at finding the matches. 

Or you could run ipmatch with a big outlier factor to let in a lot of outliers, and then do your own filtering with opencv, but that one has only estimateAffine2D and findHomography as options, as I see. (https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html)

**Comment by oleg-alexandrov** [comment]
The image_align program can apply a translation constraint on interest point matches.
