### ISSUE TITLE
Python binding for Camera

### ISSUE THREAD

**Issue by ghislainp** [visionworkbench/visionworkbench#66]
Is there any python bindings to access the Camera ?
I'd would like to perform sensitivity analysis of the orthorectification (mapproject in ASP) to the intrinsic/extrinsic parameters of the camera. That would be more comfortable in python...

**Comment by oleg-alexandrov** [comment]
We don't have python bindings to any ASP functions, regretfully. It does not have enough support or use to justify working on such things. 

I guess your best bet is to have a python tool repeatedly create camera files, write them to disk, invoke the desired tools, and read the results back. 

Or, you can build ASP from source. That got quite a lot easier recently as all its dependencies and tools can be fetched via conda, so it should be rather straightforward and not depend too much the specifics of the local machine. That is described here: https://stereopipeline.readthedocs.io/en/latest/installation.html#building-asp-from-source. Still not trivial work though.
