### ISSUE TITLE
out of date installation instructions

### ISSUE THREAD

**Issue by AndrewAnnex** [visionworkbench/visionworkbench#67]
it looks like the project has transitioned to use cmake but the documentation still discusses autotools bits like ./configure which are now absent from the repository. looking at the cmake files it looks like there should be a whole new set of new instructions are needed to document how to compile given the dependencies on the ASP_DEPS_DIR which sounds like is relying on a conda environment for asp

**Comment by oleg-alexandrov** [comment]
I updated the page at https://github.com/visionworkbench/visionworkbench/blob/master/INSTALLGUIDE. 

Likely you will not need to actually build VisionWorkbench to get work done, but if you are feeling adventurous you can give it a try.
