### ISSUE TITLE
gdal bug?

### ISSUE THREAD

**Issue by khusmann** [visionworkbench/visionworkbench#8]
Sometimes, when I create a DiskImageResourceGDAL like so:
    DiskImageResourceGDAL out_rsrc("foo.tif", source.format(), Vector2i(1024, 1024));
I get the error:
    ERROR 4: `foo.tif' not recognised as a supported file format.
Has anyone else seen this?

**Comment by ScottMcMichael** [comment]
Need a test case to address this.
